Click to copy, Text Highlight & other improvements
wireui/docs pull request #10
Opened 2022-01-25 17:59 UTC by dansysanalyst

Hi Pedro,

Following some of our conversations, I have prepared this PR with new features and small enhancements. 

## Changes
 
- Introduce section troubleshooting. This page directs the user to the `changelog` where the upgrade guide is available. I believe it's possible that less experienced users wouldn't have the insight to search the changelog for information. 
- Re-arranged the menu to promote "user journey" and clarify the types of components (still a work in progress).
- Replaced static year with current-date-year on the footer.
- Small tweaks on texts here and there to improve readability. 
- Added some emoji icon to `Playground` to call attention.
- Added  a suggestion to run `artisan serve` after the completion of ./run.sh

<img width="875" alt="call attention to nice feature" src="https://user-images.githubusercontent.com/79267265/150995404-f651edc4-279f-412c-b552-d07cebfe7384.png">

## New Features

- **Click to copy button**: To provide an easier interactivity with the doc, all `<x-code>` components will now have a `copy` button.

<img width="797" alt="CleanShot 2022-01-25 at 15 10 53@2x" src="https://user-images.githubusercontent.com/79267265/150992549-790d44c2-7bb2-450d-8ff6-0f1c19f32b9e.png">

However, some code blocks should not have a copy button, for example when we demonstrate a Terminal output text. For these cases, we can use `<x-code-no-copy>`.

<img width="878" alt="CleanShot 2022-01-25 at 15 22 54@2x" src="https://user-images.githubusercontent.com/79267265/150994522-5c6d5eb3-0db4-4f09-b51e-3c5f4c0cd73b.png">

- **Text highlight**: Sometimes we want to call user's attention to a specific paragraph or clearly highlight a command or technical word out of the sentence. I introduced the component `<x-green>` to do just that.

Example: 

<img width="838" alt="CleanShot 2022-01-25 at 18 54 18@2x" src="https://user-images.githubusercontent.com/79267265/151032148-fa9b293c-3deb-41ad-b35c-f27c61e99a11.png">

```html
<p id="installing-package">If you have encountered the error 
<x-green>TypeError: require(...) is not a function</x-green></p>
```

Thanks,

Dan

2022-01-25 19:29 UTC, vs0uz4 commented
Oh my God! What a beautiful `PR`, look at that discretion, that richness of content. 
Congratulations, that is a (PR) at the professional level 🔥🔥🔥.

2022-01-26 02:22 UTC, PH7-Jack commented
I'm without words to describe. That is amazing. Thanks so much, @dansysanalyst

2022-01-26 04:02 UTC, PH7-Jack requested changes
@dansysanalyst Thanks for your contribution. Can you do some corrections?

2022-01-26 04:02 UTC, PH7-Jack commented on resources/views/components/code-no-copy.blade.php
> +@props(['language', 'code' => null, 'contents' => null])
I think that we don't need to add a new component, just add a new prop to disallow copy
```
@props([
    'language',
    'code'     => null,
    'contents' => null
    'noCopy' => false
])

<pre @unless ($noCopy) data-nocopy="true" @endunless>
<x-torchlight-code
    {{ $attributes}}
    :contents="$contents"
    :language="$language">
@unless ($contents)
{!! $code ?? $slot !!}
@endunless
</x-torchlight-code>
</pre>
```

2022-01-26 10:27 UTC, dansysanalyst commented on resources/views/components/green.blade.php
> +<span class="px-2 py-2 font-mono text-sm font-semibold text-gray-900 bg-teal-100 rounded-md">{{ $slot }}</span>
This is an odd one for me, Pedro. Firstly, I had it beautified, like you suggest, but this introduces an extra space. I am not sure why. WHen it's all in one line, it doesn't happen:


![CleanShot 2022-01-26 at 11 24 30@2x](https://user-images.githubusercontent.com/79267265/151146856-0f5e4cfb-8781-49c0-95d9-6be0614c5448.png)

2022-01-26 10:52 UTC, dansysanalyst commented on resources/views/components/code-no-copy.blade.php
> +@props(['language', 'code' => null, 'contents' => null])
Hi Pedro,

Originally, I went with the idea of passing a propriety which would arrive to something like `<x-code nocopy>`.

PRO: This would allow us to have more flexibility like: `<x-code no-copy no-torchlight no-line-numbers>` and so on...

Then I thought it would be unlike that we have a need for customization in a doc and I decided to separate in different components to keep it well divided and, hopefully, cleaner for new contributor to see what is available.

One just have to see the `components` folder and read `code`, `code-no-copy`, `info`, `attention` in rival to having to dig inside the code or read the "doc of the doc" to see what proprieties `x-code` or `x-block` accept.

This is a matter of opinion and I can sure change it back matching your suggestion. Just curious to see what you think of it!

Thanks

2022-01-26 15:13 UTC, PH7-Jack commented on resources/views/components/green.blade.php
> +<span class="px-2 py-2 font-mono text-sm font-semibold text-gray-900 bg-teal-100 rounded-md">{{ $slot }}</span>
Are you right, ignore this suggestion

2022-01-27 02:51 UTC, PH7-Jack commented on resources/views/components/code-no-copy.blade.php
> +@props(['language', 'code' => null, 'contents' => null])
I understand your idea. But, is so boring to manage all props using a new component, `<x-code ... /> <x-code-no-copy /> <x-code-foo /> ...`
We can manage all features into one component. I like this idea when the component will be different from the original. 
I appreciate your opinion, but to make it more flexible, I think that must be a prop into the `<x-code />` component

2022-01-27 02:51 UTC, PH7-Jack commented on resources/views/components/code-no-copy.blade.php
> +@props(['language', 'code' => null, 'contents' => null])
Really, I'm sooo happy with your contribution. Thank you, man

2022-01-27 15:13 UTC, dansysanalyst commented on resources/views/components/code-no-copy.blade.php
> +@props(['language', 'code' => null, 'contents' => null])
I must agree with your point. I've refactored the new components to fit this strategy and updated the README.

2022-01-31 05:37 UTC, PH7-Jack commented on tests/Feature/resources/views/components/ComponentsTest.php
> +});
A tip about component testing:
Don't need to assert the rendered HTML, it is frequently changed, the most important is to assert if the information is showing in the rendered HTML.

example
```
test('x-code renders with Torchlight', function () {
    $view = $this->blade('<x-code language="shell" code="composer require wireui/wireui" />');

    $view->assertSeeText('composer require wireui/wireui');
});
```

2022-01-31 05:41 UTC, PH7-Jack commented on resources/views/components/box.blade.php
> +@props(['attention' => false,'info' => false])
This file has two components, split it 
it can be:
```
alerts.info
alerts.warning
alerts.foo
```
It will be more simple to maintain and the cache will be better

2022-01-31 06:02 UTC, PH7-Jack commented on resources/views/components/code.blade.php
> +@endunless
We can enhance it and allow all torchlight options. Ex https://torchlight.dev/docs/options/line-numbers

```
@props([
    'language',
    'code'     => null,
    'contents' => null,
    'copy'     => true,
    'options'  => false,
])

<pre @unless($copy) data-nocopy="true" @endunless>
<x-torchlight-code
    {{ $attributes}}
    :contents="$contents"
    :language="$language">
@unless ($contents)
@if($options)
// torchlight! {!! $options !!}
@endif
{!! $code ?? $slot !!}
@endunless
</x-torchlight-code>
</pre>
```

Example of usage
```
<x-code language="ts" options="{ lineNumbers: false, ... }" :code="<<<EOT
{
    title: 'Notification Title',
    description: 'It can be nullable too',
    icon: 'success'
}
EOT" />
```

2022-01-31 10:11 UTC, dansysanalyst commented
Pedro, your reviews are awesome! 🙏

It is really good to interact, see another point of view, improve technical concepts.

Thanks

2022-01-31 10:21 UTC, dansysanalyst commented on tests/Feature/resources/views/components/ComponentsTest.php
> +});
Hi Pedro,

I intended to make sure that x-code is rendering with Torchlight and maybe write a specific test regarding the proprieties we pass. Something in the line of "my component still works if remove the line numbers?"

The `assertSeeText`, would still pass if the Torchlite is broken, right?

2022-02-03 04:46 UTC, PH7-Jack approved these changes
@dansysanalyst Thanks so much for your contribution. It will enhance the wireui docs. You are an amazing guy

2022-02-03 04:48 UTC, merged